apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: {{ .Values.castDb.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.castDb.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.castDb.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.castDb.database | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: cast-db
  ports:
    - port: 5432
      targetPort: 5432
